db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

client:
    ClusterID: "test-cluster"
    ClientID: "stan-sub"
    Subject: "foo"
    